version: '3.0'

services:
  product-api-server:
    image: jbonu/product-api-image:1.0.3
    restart: always
    ports:
      - "3000:3000"
    networks:
      - product-api-network
    command: node app.js

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379

  cassandra:
    image: docker.io/bitnami/cassandra:4.0.12
    container_name: bitnami-cassandra-v1
    ports:
      - '7000:7000'
      - '9042:9042'
    volumes:
      - ./schema/cassandra:/docker-entrypoint-initdb.d
      - 'cassandra_data:/bitnami'
    healthcheck:
      test: [ "CMD", "/opt/bitnami/cassandra/bin/cqlsh", "-u cassandra", "-p cassandra" ,"-e \"describe keyspaces\"" ]
      interval: 15s
      timeout: 10s
      retries: 10
    environment:
      - CASSANDRA_USER=cassandra
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
    networks:
      - product-api-network
    restart: always

volumes:
  cassandra_data:
    driver: local

networks:
  product-api-network: