apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: cassandra-claim0
  name: cassandra-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
